### ISSUE TITLE
Get ticker real-time price and compare to actual price

### ISSUE THREAD

**Issue by HarshalNallapareddy** [Project-Code-UVA/VizOp#1]
1. Get the Ticker and current price of Ticker. URL: https://api.marketdata.app/v1/stocks/quotes/AAPL/

Compare price from JSON and stock quotes API to real time price. May need to get live price from other API (alphavantage)

**Comment by HarshalNallapareddy** [comment]
Hey Prithvi, let me know if you need help with the assignment? I'll be happy to work with you

**Comment by prithvi-seri** [comment]
Just added my code to algo.py.
