### ISSUE TITLE
Get option type, greeks, and implement response check

### ISSUE THREAD

**Issue by HarshalNallapareddy** [Project-Code-UVA/VizOp#3]
1. Get the option type (call or put) from JSON 
2. Retrieve the greeks from JSON
3. Check if the response is valid (can use respone.status_code and/or first field in JSON)

**Comment by patrickgilmartin** [comment]
Code (in Python):

//////////////////////////////////////// START

import requests

url = "https://api.marketdata.app/v1/options/quotes/AAPL250117C00150000/"

response = requests.get(url)

if response.status_code == 200:
    data = response.json()

    # Get the option type (call or put) from the 'side' field in JSON
    option_type = data["side"][0]

    # Retrieve the greek values from the JSON
    greeks = {
        "delta": data["delta"][0],
        "gamma": data["gamma"][0],
        "theta": data["theta"][0],
        "vega": data["vega"][0],
        "rho": data["rho"][0]
    }

    # Check if the response is valid based on the 's' field in JSON
    if data.get("s") == "ok":
        print(f"Option Type: {option_type}")
        print("Greek Values:")
        for key, value in greeks.items():
            print(f"{key}: {value}")
    else:
        print("Invalid response.")
else:
    print("Failed to retrieve data. Status code:", response.status_code)

//////////////////////// END

Output (as per the provided code):

Option Type: call
Greek Values:
delta: 0.763
gamma: 0.005
theta: -0.028
vega: 0.57
rho: 1.156

**Comment by patrickgilmartin** [comment]
`import requests

url = "https://api.marketdata.app/v1/options/quotes/AAPL250117C00150000/"

response = requests.get(url)

if response.status_code == 200:
    data = response.json()

    # Get the option type (call or put) from the 'side' field in JSON
    option_type = data["side"][0]

    # Retrieve the greek values from the JSON
    greeks = {
        "delta": data["delta"][0],
        "gamma": data["gamma"][0],
        "theta": data["theta"][0],
        "vega": data["vega"][0],
        "rho": data["rho"][0]
    }

    # Check if the response is valid based on the 's' field in JSON
    if data.get("s") == "ok":
        print(f"Option Type: {option_type}")
        print("Greek Values:")
        for key, value in greeks.items():
            print(f"{key}: {value}")
    else:
        print("Invalid response.")
else:
    print("Failed to retrieve data. Status code:", response.status_code)
`

**Comment by HarshalNallapareddy** [comment]
Hey Patrick, do you think you can add this to our code?

**Comment by patrickgilmartin** [comment]
Hi Harshal, I believe I just did there now. Let me know if you see it / if
it was uploaded correctly. Thank you.

**Comment by HarshalNallapareddy** [comment]
Nice work! I'll make a few changes and push it to main
